export const INDIAN_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry"
];

export const DESIGNATIONS = [
    "Owner / मालिक",
    "Top Management / शीर्ष प्रबंधन",
    "Restaurant Manager / रेस्टोरेंट प्रबंधक",
    "Operations / संचालन",
    "Kitchen Incharge / किचन इंचार्ज",
    "Online Orders / ऑनलाइन ऑर्डर",
    "Accounts / खाते",
    "Purchase / खरीद",
    "Floor Incharge / फ्लोर इंचार्ज",
    "Main Contact / मुख्य संपर्क"
]